BU Arts Initiative: Profile Page (profile photo upload, event registration)
BU-Spark/se-bu-passport-arts pull request #9
Opened 2024-03-26 03:04 UTC by lcfmarco

- Photo upload logic
- Registered events in explore page added to user schema
- Registered events showcased in profile page

2024-03-27 01:15 UTC, molly-yan requested changes
Good work! Just a few places need adjustments:
- Replace magic numbers with dynamic measurement.
- Removed unused code piece

2024-03-27 01:15 UTC, molly-yan commented on bu_passport/lib/pages/profile_page.dart
>                        SizedBox(height: 8),
Replace magic number with dynamic measurement

2024-03-27 01:15 UTC, molly-yan commented on bu_passport/lib/pages/profile_page.dart
>                      SizedBox(height: 8),
Replace magic number with dynamic measurement

2024-03-27 01:15 UTC, molly-yan commented on bu_passport/lib/pages/profile_page.dart
> +                    // ElevatedButton(
Removed unused code piece

2024-03-27 23:23 UTC, lcfmarco commented
I just updated the file with the requested changes, pushed onto the profile page branch (I assume that is what I am meant to do with the requested changes? So hopefully it's all good and that you see it!)

2024-03-28 23:42 UTC, molly-yan approved these changes
lgtm. Please resolve the conflict, then you're good to merge.

2024-04-01 05:37 UTC, merged